#cloud-config
# source: https://thenewstack.io/deploy-a-kubernetes-cluster-on-ubuntu-server-with-microk8s/
users:
- name: ubuntu
  sudo: ALL=(ALL) NOPASSWD:ALL
  groups: users, admin, microk8s
  home: /home/ubuntu
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCPyuU50F4ZV8SgP2luVJZPgHAH1zTtEmxblIbgQhAbFfxHDBFH7fmM7zJ+PrC4wILuDmv2t1eDT3sMR2ZeP1/Su//+pxauInVx/UlhQzS0e0BQvPuWkG3GHcUptXZ4XHyFw6sny/qixxfXgwAczETexk9MY8g8VXQ8LjTIAGXbn9iy4dDVYPF+pnQhlztH7qwaq0OhENojbAem+pAV2744+tRDfmHaTriRQPkKhM+17hBxX0DqaUWH/kOELUA57QCzzq8Sd+UNI0tvZnXwl3m4KVbMfs+QyMQwPItZtxCGmDP+2pitZOzk2zeAi76xav4CeKlJwCqAwt1FsKUugA/Z bog
groups:
- microk8s
system_info:
  default_user:
    groups: [microk8s]
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
- curl
runcmd:
- sudo snap install microk8s --classic
- mkdir /home/ubuntu/.kube


